// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3853.Charlie2016;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainleftMotor;
    public static SpeedController driveTrainRightMotor;
    public static RobotDrive driveTrainRobotDrive21;
    public static Encoder driveTrainLeftDriveEncoder;
    public static Encoder driveTrainrightDriveEncoder;
    public static SpeedController armarmMotor;
    public static DigitalInput armArmHomeSwitch;
    public static Encoder armarmEncoder;
    public static SpeedController ballHandlerballMotor;
    public static DigitalInput ballHandlerballPresentSwitch;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainleftMotor = new Talon(0);
        LiveWindow.addActuator("DriveTrain", "leftMotor", (Talon) driveTrainleftMotor);
        
        driveTrainRightMotor = new Talon(1);
        LiveWindow.addActuator("DriveTrain", "RightMotor", (Talon) driveTrainRightMotor);
        
        driveTrainRobotDrive21 = new RobotDrive(driveTrainleftMotor, driveTrainRightMotor);
        
        driveTrainRobotDrive21.setSafetyEnabled(true);
        driveTrainRobotDrive21.setExpiration(0.1);
        driveTrainRobotDrive21.setSensitivity(0.5);
        driveTrainRobotDrive21.setMaxOutput(1.0);

        driveTrainLeftDriveEncoder = new Encoder(3, 4, false, EncodingType.k1X);
        LiveWindow.addSensor("DriveTrain", "LeftDriveEncoder", driveTrainLeftDriveEncoder);
        driveTrainLeftDriveEncoder.setDistancePerPulse(0.052);
        driveTrainLeftDriveEncoder.setPIDSourceType(PIDSourceType.kDisplacement);
        driveTrainrightDriveEncoder = new Encoder(5, 6, false, EncodingType.k1X);
        LiveWindow.addSensor("DriveTrain", "rightDriveEncoder", driveTrainrightDriveEncoder);
        driveTrainrightDriveEncoder.setDistancePerPulse(0.052);
        driveTrainrightDriveEncoder.setPIDSourceType(PIDSourceType.kDisplacement);
        armarmMotor = new Talon(8);
        LiveWindow.addActuator("Arm", "armMotor", (Talon) armarmMotor);
        
        armArmHomeSwitch = new DigitalInput(2);
        LiveWindow.addSensor("Arm", "ArmHomeSwitch", armArmHomeSwitch);
        
        armarmEncoder = new Encoder(0, 1, false, EncodingType.k1X);
        LiveWindow.addSensor("Arm", "armEncoder", armarmEncoder);
        armarmEncoder.setDistancePerPulse(0.724);
        armarmEncoder.setPIDSourceType(PIDSourceType.kDisplacement);
        ballHandlerballMotor = new Talon(9);
        LiveWindow.addActuator("BallHandler", "ballMotor", (Talon) ballHandlerballMotor);
        
        ballHandlerballPresentSwitch = new DigitalInput(7);
        LiveWindow.addSensor("BallHandler", "ballPresentSwitch", ballHandlerballPresentSwitch);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
